import type { ChannelPreset } from './types.ts'

export const CHANNEL_PRESETS: readonly ChannelPreset[] = [
  {
    id: 'nature',
    number: 1,
    name: 'Nature & Wildlife',
    description: 'Breathtaking nature documentaries and wildlife footage from BBC Earth',
    playlistId: 'PLjT9m667OZDP23S2BxUbMRdqnVTg5PMDA',
    emoji: '🌿',
  },
  {
    id: 'space',
    number: 2,
    name: 'Space & NASA',
    description: 'Journey through the cosmos with NASA videos and space exploration content',
    playlistId: 'PLTiv_XWtigLWqmF2KnJzJ9ZS5u_UVWMRP',
    emoji: '🚀',
  },
  {
    id: 'retro-tech',
    number: 3,
    name: 'Retro Tech',
    description: 'Old computers, vintage technology, and the history of the digital age',
    playlistId: 'PLbpi6ZahtOH6Ar_3GPy3workVs3G3Xm0V',
    emoji: '💾',
  },
  {
    id: 'jazz',
    number: 4,
    name: 'Jazz Lounge',
    description: 'Classic and contemporary jazz — bebop, fusion, standards, and beyond',
    playlistId: 'PLH-Ejjp5HV5q8EkCNRhSXNBUWjV4ATNMS',
    emoji: '🎷',
  },
  {
    id: 'ted',
    number: 5,
    name: 'TED Talks',
    description: 'Ideas worth spreading — talks on science, culture, and the human condition',
    playlistId: 'PLJicmE8fK0EiEzttYMD1zYkT-SmNf323z',
    emoji: '🎤',
  },
  {
    id: 'lofi',
    number: 6,
    name: 'Lo-Fi Beats',
    description: 'Chill lo-fi hip hop beats to study, relax, and zone out to',
    playlistId: 'PLofht4DKzD7zOWhfxBpBhK3UlVXOXMfvV',
    emoji: '🎧',
  },
  {
    id: 'cooking',
    number: 7,
    name: 'Cooking Channel',
    description: 'Recipes, techniques, and food culture from around the world',
    playlistId: 'PLIhvC209hCEBFVXXhwGFTlBHZ7M7JhPep',
    emoji: '🍳',
  },
  {
    id: 'travel',
    number: 8,
    name: 'Travel & Geography',
    description: 'Explore destinations, cultures, and landscapes across the globe',
    playlistId: 'PLumgODnJSLJzMkONWIE1xjf-fM4mPQNl7',
    emoji: '✈️',
  },
  {
    id: 'science',
    number: 9,
    name: 'Science & Physics',
    description: 'Kurzgesagt and friends explain the universe in animated clarity',
    playlistId: 'PLFs4vir_WsTwEd-nJgVJCZPNL3HALHHpF',
    emoji: '⚛️',
  },
  {
    id: 'comedy',
    number: 10,
    name: 'Comedy Central',
    description: 'Stand-up sets, sketches, and comedy shorts to keep you laughing',
    playlistId: 'PLkIApjSIBhOGrBMxrXxAtBl9wHaLZi0M6',
    emoji: '😂',
  },
  {
    id: 'history',
    number: 11,
    name: 'History Vault',
    description: 'Documentaries and deep dives into pivotal moments in human history',
    playlistId: 'PLbMkMkKGGULXyJi5QASN4kJbPQZT1R4aZ',
    emoji: '📜',
  },
  {
    id: 'classical',
    number: 12,
    name: 'Classical Music',
    description: 'Orchestral masterworks, concertos, and chamber music from the great composers',
    playlistId: 'PLqOia6O5iTGQ7C2VTq83XPuvnEjIcipUm',
    emoji: '🎻',
  },
] as const
