import type { ChannelPreset } from './types.ts'

export const CHANNEL_PRESETS: readonly ChannelPreset[] = [
  {
    id: 'skate',
    number: 1,
    name: 'Skate Vids',
    description: 'Skateboarding clips and edits',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsiBYTWTmljl4E3Ft0DBVlDH',
    emoji: '🛹',
  },
  {
    id: 'music',
    number: 2,
    name: 'Music Videos',
    description: 'Music videos from the collection',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHshjqFKDhoSFjVLtyVOnOaOn',
    emoji: '🎵',
  },
  {
    id: 'party',
    number: 3,
    name: 'Party Background',
    description: 'Background vibes for any occasion',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsg9L_50qUKKeTYa3CR33o9s',
    emoji: '🎉',
  },
  {
    id: 'favorites',
    number: 4,
    name: 'Favorites',
    description: 'All-time favorite videos',
    kind: 'video' as const,
    playlistId: 'FLRbSMOWF7L-IrYVrZ0qBRfw',
    emoji: '⭐',
  },
  {
    id: 'entertainment',
    number: 5,
    name: 'Entertainment',
    description: 'Entertainment picks from around the web',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsgXkkeyJM1E8-Lx28ds32Nt',
    emoji: '📺',
  },
  {
    id: 'club-krunz',
    number: 6,
    name: 'Club Krünz',
    description: 'The club never closes',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsjM5E1QSC1BTb7mE6YsOL0Z',
    emoji: '🪩',
  },
  {
    id: 'live-music',
    number: 7,
    name: 'Live Music',
    description: 'Live performances and concert footage',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsgOwvlmX382R3mfmghM5BZ3',
    emoji: '🎸',
  },
  {
    id: 'electronic-mixes',
    number: 8,
    name: 'Mixes and Sets',
    description: 'DJ mixes and extended sets',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsjFc_P7McjUhcELpscfWoag',
    emoji: '🎛️',
  },
  {
    id: 'slow',
    number: 9,
    name: 'Slow',
    description: 'Slow and steady',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsijEtzJ4WhbwchG_fTU1e_4',
    emoji: '🐢',
  },
  {
    id: 'patagonia-surfing',
    number: 10,
    name: 'Patagonia | Surfing',
    description: 'Surfing in Patagonia',
    kind: 'video' as const,
    playlistId: 'PL58D86239D8EE4A6A',
    emoji: '🏄',
  },
  {
    id: 'radio-soulwax',
    number: 11,
    name: 'Radio Soulwax',
    description: 'Radio Soulwax broadcasts',
    kind: 'video' as const,
    playlistId: 'PL5PnoBesS3Uyv2mgkgCnEBhOeD0YE97OO',
    emoji: '📻',
  },
  {
    id: 'funny',
    number: 12,
    name: 'Funny',
    description: 'Comedy clips and funny videos',
    kind: 'video' as const,
    playlistId: 'PLmDOmgjgiHsg1V4vIR7XhgheeB-PT1KtU',
    emoji: '😂',
  },
  {
    id: 'headbangers-ball',
    number: 13,
    name: 'Headbangers Ball',
    description: 'Heavy metal and hard rock',
    kind: 'video' as const,
    playlistId: 'PLFGIvt16_DQYoyVuvl9Cy1vK7tE0fgFMP',
    emoji: '🤘',
  },
  {
    id: 'bumbershoot-gardyloo',
    number: 14,
    name: 'Bumbershoot Gardyloo',
    description: 'Bumbershoot festival performances',
    kind: 'video' as const,
    playlistId: 'PLQxh1ekjHJ2UNYqrSzC-lJ4j6ZjgtaiF8',
    emoji: '🎪',
  },
  {
    id: 'caribou-mixtape',
    number: 15,
    name: 'Caribou Mixtape',
    description: 'Caribou — The Longest Mixtape',
    kind: 'video' as const,
    playlistId: 'PL4lEESSgxM_5O81EvKCmBIm_JT5Q7JeaI',
    emoji: '🫎',
  },
  {
    id: 'sc-calming',
    number: 16,
    name: 'Calming',
    description: 'Calming SoundCloud set',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/calming',
    emoji: '🌙',
  },
  {
    id: 'sc-all-time-favorites',
    number: 17,
    name: 'All Time Favorites',
    description: 'Krünz all-time favorite tracks',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/all-time-favorites',
    emoji: '💛',
  },
  {
    id: 'sc-strato-krunz',
    number: 18,
    name: 'Strato & Krünz',
    description: 'Strato & Krünz collaborations',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/strato-kr-nz',
    emoji: '🎚️',
  },
  {
    id: 'sc-eclectic',
    number: 19,
    name: 'Eclectic',
    description: 'Eclectic SoundCloud set',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/eclectic',
    emoji: '🎨',
  },
  {
    id: 'sc-deeply-disco',
    number: 20,
    name: 'Deeply Disco',
    description: 'Deep disco grooves',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/deep-disco',
    emoji: '🪩',
  },
  {
    id: 'sc-2016-sets',
    number: 21,
    name: '2016 Sets',
    description: 'Sets from 2016',
    kind: 'music' as const,
    source: 'soundcloud' as const,
    sourceUrl: 'https://soundcloud.com/krunz/sets/2016-sets',
    emoji: '📼',
  },
] as const
