/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/_tv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'
import { Route as ApiSoundcloudRouteImport } from './routes/api/soundcloud'
import { Route as TvChannelChannelIdRouteImport } from './routes/_tv.channel.$channelId'

const TvRoute = TvRouteImport.update({
  id: '/_tv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundcloudRoute = ApiSoundcloudRouteImport.update({
  id: '/api/soundcloud',
  path: '/api/soundcloud',
  getParentRoute: () => rootRouteImport,
} as any)
const TvChannelChannelIdRoute = TvChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => TvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/soundcloud': typeof ApiSoundcloudRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/soundcloud': typeof ApiSoundcloudRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tv': typeof TvRouteWithChildren
  '/api/soundcloud': typeof ApiSoundcloudRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/_tv/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/soundcloud' | '/api/youtube' | '/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/soundcloud' | '/api/youtube' | '/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_tv'
    | '/api/soundcloud'
    | '/api/youtube'
    | '/_tv/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TvRoute: typeof TvRouteWithChildren
  ApiSoundcloudRoute: typeof ApiSoundcloudRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tv': {
      id: '/_tv'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundcloud': {
      id: '/api/soundcloud'
      path: '/api/soundcloud'
      fullPath: '/api/soundcloud'
      preLoaderRoute: typeof ApiSoundcloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tv/channel/$channelId': {
      id: '/_tv/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof TvChannelChannelIdRouteImport
      parentRoute: typeof TvRoute
    }
  }
}

interface TvRouteChildren {
  TvChannelChannelIdRoute: typeof TvChannelChannelIdRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvChannelChannelIdRoute: TvChannelChannelIdRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TvRoute: TvRouteWithChildren,
  ApiSoundcloudRoute: ApiSoundcloudRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
