/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TvRouteImport } from './routes/_tv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChannelsRouteImport } from './routes/api/channels'
import { Route as TvChannelChannelIdRouteImport } from './routes/_tv.channel.$channelId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/_tv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsRoute = ApiChannelsRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const TvChannelChannelIdRoute = TvChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => TvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/channels': typeof ApiChannelsRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/channels': typeof ApiChannelsRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tv': typeof TvRouteWithChildren
  '/about': typeof AboutRoute
  '/api/channels': typeof ApiChannelsRoute
  '/_tv/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/api/channels' | '/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/api/channels' | '/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_tv'
    | '/about'
    | '/api/channels'
    | '/_tv/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TvRoute: typeof TvRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiChannelsRoute: typeof ApiChannelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tv': {
      id: '/_tv'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tv/channel/$channelId': {
      id: '/_tv/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof TvChannelChannelIdRouteImport
      parentRoute: typeof TvRoute
    }
  }
}

interface TvRouteChildren {
  TvChannelChannelIdRoute: typeof TvChannelChannelIdRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvChannelChannelIdRoute: TvChannelChannelIdRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TvRoute: TvRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiChannelsRoute: ApiChannelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
