/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/_tv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as ApiSharesRouteImport } from './routes/api/shares'
import { Route as ApiChannelsRouteImport } from './routes/api/channels'
import { Route as TvChannelChannelIdRouteImport } from './routes/_tv.channel.$channelId'

const TvRoute = TvRouteImport.update({
  id: '/_tv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsRoute = ApiChannelsRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const TvChannelChannelIdRoute = TvChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => TvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/channels': typeof ApiChannelsRoute
  '/api/shares': typeof ApiSharesRoute
  '/s/$shareId': typeof SShareIdRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/channels': typeof ApiChannelsRoute
  '/api/shares': typeof ApiSharesRoute
  '/s/$shareId': typeof SShareIdRoute
  '/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tv': typeof TvRouteWithChildren
  '/api/channels': typeof ApiChannelsRoute
  '/api/shares': typeof ApiSharesRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_tv/channel/$channelId': typeof TvChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/channels'
    | '/api/shares'
    | '/s/$shareId'
    | '/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/channels'
    | '/api/shares'
    | '/s/$shareId'
    | '/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_tv'
    | '/api/channels'
    | '/api/shares'
    | '/s/$shareId'
    | '/_tv/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TvRoute: typeof TvRouteWithChildren
  ApiChannelsRoute: typeof ApiChannelsRoute
  ApiSharesRoute: typeof ApiSharesRoute
  SShareIdRoute: typeof SShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tv': {
      id: '/_tv'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tv/channel/$channelId': {
      id: '/_tv/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof TvChannelChannelIdRouteImport
      parentRoute: typeof TvRoute
    }
  }
}

interface TvRouteChildren {
  TvChannelChannelIdRoute: typeof TvChannelChannelIdRoute
}

const TvRouteChildren: TvRouteChildren = {
  TvChannelChannelIdRoute: TvChannelChannelIdRoute,
}

const TvRouteWithChildren = TvRoute._addFileChildren(TvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TvRoute: TvRouteWithChildren,
  ApiChannelsRoute: ApiChannelsRoute,
  ApiSharesRoute: ApiSharesRoute,
  SShareIdRoute: SShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
